const enum ActionTypes {
  SEND_USER_REQUEST = 'SEND_USER_REQUEST',
  GET_USER_DATA = 'GET_USER_DATA',
  GET_DELIVERY_TYPE = 'GET_DELIVERY_TYPE',
  ADD_DELIVERY_TYPE = 'ADD_DELIVERY_TYPE',
  DELETE_DELIVERY_TYPE = 'DELETE_DELIVERY_TYPE',
  EDIT_DELIVERY_TYPE = 'EDIT_DELIVERY_TYPE',
}

export { ActionTypes }