const enum ActionTypes {
  SEND_USER_REQUEST = 'SEND_USER_REQUEST',
  GET_USER_DATA = 'GET_USER_DATA',
  GET_DELIVERY_TYPE = 'GET_DELIVERY_TYPE',
  ADD_DELIVERY_TYPE = 'ADD_DELIVERY_TYPE',
  DELETE_DELIVERY_TYPE = 'DELETE_DELIVERY_TYPE',
  EDIT_DELIVERY_TYPE = 'EDIT_DELIVERY_TYPE',
  GET_ARTICLE_DATA = 'GET_ARTICLE_DATA',
  ADD_ARTICLE = 'ADD_ARTICLE',
  DELETE_ARTICLE = 'DELETE_ARTICLE',
  EDIT_ARTICLE = 'EDIT_ARTICLE',
  GET_PARTNERS_DATA = 'GET_PARTNERS_DATA',
  ADD_PARTNER = 'ADD_PARTNER',
  DELETE_PARTNER = 'DELETE_PARTNER',
  EDIT_PARTNER = 'EDIT_PARTNER',
}

export { ActionTypes }