const enum MutationTypes {
  SET_USER = 'SET_USER',
  SET_ERRORS = 'SET_ERRORS',
  SET_IS_LOADING = 'SET_IS_LOADING',
  SET_DELIVERY_TYPES = 'SET_DELIVERY_TYPES',
  ADD_TO_DELIVERY_TYPES = 'ADD_TO_DELIVERY_TYPES',
  DELETE_FROM_DELIVERY_TYPES = 'DELETE_FROM_DELIVERY_TYPES',
  UPDATE_DELIVERY_TYPES = 'UPDATE_DELIVERY_TYPES',
}

export { MutationTypes }