version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - backend/.env.dev
    networks:
      - backend

  core:
    build:
      context: backend
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  db:
