version: '3.9'

services:
  db:
    image: postgres:15.1
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - backend/.env.prod

  backend:
    build:
      context: backend
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend:/backend
    expose:
      - 8000
    depends_on:
      - db

  nginx:  # Copy static files during building this container
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'  # for images
      - '443:443'  # for https
    volumes:
      - /root/images:/usr/share/nginx/images/

  redis:
    image: redis:latest
