version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - '5433:5432'
    env_file:
      - backend/.env.dev
    networks:
      - backend

  backend:
    build:
      context: backend
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: front
      dockerfile: ./build/Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - backend
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  db:
