version: '3.8'

services:
  #  Backend part
  db:
    container_name: 'dev_db'
    image: postgres:15.1
    env_file:
      - backend/.env.dev
    ports:
      - '5434:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

  parser:
    container_name: 'dev_parser'
    build:
      context: backend
      dockerfile: ./build/Dockerfile
      target: parser
    depends_on:
      db:
        condition: service_healthy

  backend:
    container_name: 'dev_backend'
    build:
      context: backend
      dockerfile: ./build/Dockerfile
      target: backend
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../data/site_media:/site_media
      - ./backend:/backend

#  redis:
#    container_name: 'dev_redis'
#    image: redis:latest
#    ports:
#      - '6379:6379'
#    healthcheck:
#      test: [ "CMD", "redis-cli","ping" ]

  #  Frontend part
  admin_dashboard:
    container_name: 'dev_admin_dashboard'
    build:
      context: admin
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    ports:
      - '8001:8001'

  frontend:
    container_name: 'dev_frontend'
    build:
      context: ssr
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    ports:
      - '8002:8002'

  reverse_proxy: # Copy static files during building this container
    container_name: 'dev_reverse_proxy'
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'  # for https
      - '8010:8010'  # for images and static files
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
      admin_dashboard:
        condition: service_started
    volumes:
      - ./data/site_media:/usr/share/nginx/site_media/
      - ./reverse_proxy/dev.conf:/etc/nginx/conf.d/dev.conf
