version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - '5433:5432'
    env_file:
      - backend/.env.dev

  backend:
    build:
      context: backend
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  nginx:  # Copy static files during building this container
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'  # for https
        
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

