version: '3.9'

services:
  db:
    image: postgres
    ports:
    - '5433:5432'
    env_file:
      - backend/.env.dev

  core:
    build:
      context: backend
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - '8000:8000'
    env_file:
      - backend/.env.dev
    depends_on:
      - db
