# There are all models whose migrations are autogenerated by alembic.
from src.models.attribute_model import Attribute
from src.models.base_unit_model import BaseUnit
from src.models.cart_model import Cart
from src.models.category_model import Category
from src.models.manufacturer_model import Manufacturer
from src.models.product_attribute_model import ProductAttribute
from src.models.product_models import Product
from src.models.user_model import User
from src.models.watchlist_model import WatchList
