"""Add watchlists, carts, base_units, product_attributes models and change old models

Revision ID: 0e1ea67467c3
Revises: 65c4fb0d120d
Create Date: 2022-12-10 15:36:29.330317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1ea67467c3'
down_revision = '65c4fb0d120d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('bookkeeping_id', sa.String(length=128), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookkeeping_id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_attributes_id'), 'attributes', ['id'], unique=False)
    op.create_table('base_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('international_abbreviated', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_units_id'), 'base_units', ['id'], unique=False)
    op.create_table('product_attribute',
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('attribute_id', 'product_id')
    )
    op.add_column('products', sa.Column('base_unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'base_units', ['base_unit_id'], ['id'])
    op.drop_column('products', 'base_unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('base_unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'base_unit_id')
    op.drop_table('product_attribute')
    op.drop_index(op.f('ix_base_units_id'), table_name='base_units')
    op.drop_table('base_units')
    op.drop_index(op.f('ix_attributes_id'), table_name='attributes')
    op.drop_table('attributes')
    # ### end Alembic commands ###
