"""Change name of a field in order model

Revision ID: 0e9df5bf5f78
Revises: 6c15c3fb75e4
Create Date: 2023-02-18 15:04:02.383709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9df5bf5f78'
down_revision = '6c15c3fb75e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('street', sa.String(length=128), nullable=True))
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('orders', 'street')
    # ### end Alembic commands ###
