"""add odering for categories

Revision ID: 11ca0ba53c0d
Revises: 546b1238a91c
Create Date: 2023-01-04 19:17:30.366425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ca0ba53c0d'
down_revision = '546b1238a91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'order')
    # ### end Alembic commands ###
