"""Change image path

Revision ID: 14ec0e95dea2
Revises: f8f73c62f691
Create Date: 2022-05-29 23:44:30.109550

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '14ec0e95dea2'
down_revision = 'f8f73c62f691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('products', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'price')
    op.drop_column('products', 'image_path')
    # ### end Alembic commands ###
