"""Add product type

Revision ID: 2e6be17cc062
Revises: 0e1ea67467c3
Create Date: 2022-12-11 21:15:49.373812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from src.core.enums import ProductType

revision = '2e6be17cc062'
down_revision = '0e1ea67467c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    product_type = sa.Enum(*ProductType.values(), name="type")
    product_type.create(op.get_bind(), checkfirst=True)
    op.add_column('products', sa.Column('type', postgresql.ENUM(*ProductType.values(), name='type'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'type')
    status = sa.Enum(ProductType.values(), name="type")
    status.drop(op.get_bind())

    # ### end Alembic commands ###
