"""Fix models

Revision ID: 546b1238a91c
Revises: c40935377137
Create Date: 2023-01-02 12:10:37.779159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '546b1238a91c'
down_revision = 'c40935377137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('bookkeeping_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookkeeping_id')
    )
    op.create_index(op.f('ix_attribute_names_id'), 'attribute_names', ['id'], unique=False)
    op.create_table('attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('bookkeeping_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookkeeping_id')
    )
    op.create_index(op.f('ix_attribute_values_id'), 'attribute_values', ['id'], unique=False)
    op.add_column('attributes', sa.Column('value_id', sa.Integer(), nullable=True))
    op.add_column('attributes', sa.Column('name_id', sa.Integer(), nullable=True))
    op.drop_constraint('attributes_bookkeeping_id_key', 'attributes', type_='unique')
    op.drop_constraint('attributes_value_key', 'attributes', type_='unique')
    op.create_foreign_key(None, 'attributes', 'attribute_values', ['value_id'], ['id'])
    op.create_foreign_key(None, 'attributes', 'attribute_names', ['name_id'], ['id'])
    op.drop_column('attributes', 'created_at')
    op.drop_column('attributes', 'bookkeeping_id')
    op.drop_column('attributes', 'updated_at')
    op.drop_column('attributes', 'value')
    op.add_column('products', sa.Column('images', sa.String(), nullable=True))
    op.drop_column('products', 'image_path')
    op.drop_constraint('users_full_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_full_name_key', 'users', ['full_name'])
    op.add_column('products', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'images')
    op.add_column('attributes', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('attributes', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('attributes', sa.Column('bookkeeping_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('attributes', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attributes', type_='foreignkey')
    op.drop_constraint(None, 'attributes', type_='foreignkey')
    op.create_unique_constraint('attributes_value_key', 'attributes', ['value'])
    op.create_unique_constraint('attributes_bookkeeping_id_key', 'attributes', ['bookkeeping_id'])
    op.drop_column('attributes', 'name_id')
    op.drop_column('attributes', 'value_id')
    op.drop_index(op.f('ix_attribute_values_id'), table_name='attribute_values')
    op.drop_table('attribute_values')
    op.drop_index(op.f('ix_attribute_names_id'), table_name='attribute_names')
    op.drop_table('attribute_names')
    # ### end Alembic commands ###
