"""Delete an unique characteristic for an attrubute

Revision ID: 636cb81e0cbd
Revises: 2b442fc0465e
Create Date: 2022-12-25 19:04:28.194927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636cb81e0cbd'
down_revision = '2b442fc0465e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attribute_names_payload_key', 'attribute_names', type_='unique')
    op.drop_constraint('attribute_values_payload_key', 'attribute_values', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('attribute_values_payload_key', 'attribute_values', ['payload'])
    op.create_unique_constraint('attribute_names_payload_key', 'attribute_names', ['payload'])
    # ### end Alembic commands ###
