"""Add is_visible field for category and goods model, make an order argument unique

Revision ID: 758a4fadbca8
Revises: c60f001f3935
Create Date: 2023-02-04 12:59:24.526714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758a4fadbca8'
down_revision = 'c60f001f3935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'categories', ['order'])
    op.add_column('products', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_visible')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'is_visible')
    # ### end Alembic commands ###
