"""add images as a set of paths

Revision ID: b22bcdf54a9e
Revises: 2e6be17cc062
Create Date: 2022-12-21 18:59:11.340617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22bcdf54a9e'
down_revision = '2e6be17cc062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('images', sa.String(), nullable=True))
    op.drop_column('products', 'image_path')
    op.drop_constraint('users_full_name_key', 'users', type_='unique')
    op.add_column('users', sa.Column('delivery_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_full_name_key', 'users', ['full_name'])
    op.add_column('products', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'delivery_address')
    op.drop_column('products', 'images')
    # ### end Alembic commands ###
