"""change price field to decimal

Revision ID: b5b7a67afda1
Revises: 11ca0ba53c0d
Create Date: 2023-01-15 08:37:13.715043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b7a67afda1'
down_revision = '11ca0ba53c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
