"""add-a-new-field-for-user

Revision ID: c40935377137
Revises: 2e6be17cc062
Create Date: 2022-12-18 11:41:10.980834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40935377137'
down_revision = '2e6be17cc062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delivery_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delivery_address')
    # ### end Alembic commands ###
