"""Add discount attributes for products and categories

Revision ID: c60f001f3935
Revises: 7e170cb0c4af
Create Date: 2023-01-31 19:02:33.327954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60f001f3935'
down_revision = '7e170cb0c4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('price_with_discount', sa.DECIMAL(), nullable=True))
    op.add_column('products', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount')
    op.drop_column('products', 'price_with_discount')
    op.drop_column('categories', 'discount')
    # ### end Alembic commands ###
