"""Change table's name

Revision ID: c91a4888a53d
Revises: 0e9df5bf5f78
Create Date: 2023-02-18 16:14:35.233211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91a4888a53d'
down_revision = '0e9df5bf5f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_order',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_count_should_be_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'order_id')
    )
    op.drop_table('product_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_orders',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('amount > 0', name='check_count_should_be_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='product_orders_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_orders_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'order_id', name='product_orders_pkey')
    )
    op.drop_table('product_order')
    # ### end Alembic commands ###
