"""Add new model Parser Info

Revision ID: 00462ed12454
Revises: 943806c24a1c
Create Date: 2023-08-21 12:19:58.601701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00462ed12454'
down_revision = '943806c24a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service__parser_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('files_were_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_failed', sa.Boolean(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service__parser_information_id'), 'service__parser_information', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service__parser_information_id'), table_name='service__parser_information')
    op.drop_table('service__parser_information')
    # ### end Alembic commands ###
