"""Add CASCADE deleting for product_id in request calls

Revision ID: 0172a3e2f2a0
Revises: c83fc3649876
Create Date: 2023-06-15 09:25:50.847621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0172a3e2f2a0'
down_revision = 'c83fc3649876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service__request_call_product_id_fkey', 'service__request_call', type_='foreignkey')
    op.create_foreign_key(None, 'service__request_call', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service__request_call', type_='foreignkey')
    op.create_foreign_key('service__request_call_product_id_fkey', 'service__request_call', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
