"""Add price_document field

Revision ID: 0f92971a1c3f
Revises: 944ce382a1b7
Create Date: 2023-06-08 20:27:07.382706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f92971a1c3f'
down_revision = '944ce382a1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service__vendor_info', sa.Column('price_document', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service__vendor_info', 'price_document')
    # ### end Alembic commands ###
