"""add new field for category

Revision ID: 14a01b61f693
Revises: e1d6c81820ca
Create Date: 2025-06-04 15:03:55.531232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a01b61f693'
down_revision = 'e1d6c81820ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('site_page_seo_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'site_page_seo_description')
    # ### end Alembic commands ###
