"""Add logo for venodrs

Revision ID: 24c9612c2434
Revises: 8a827774614e
Create Date: 2023-03-20 12:13:49.732404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c9612c2434'
down_revision = '8a827774614e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service__vendor_info', sa.Column('logo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service__vendor_info', 'logo')
    # ### end Alembic commands ###
