"""Make vendor_code unique

Revision ID: 52cc778b746d
Revises: 531997d75f68
Create Date: 2023-07-24 11:59:07.929706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cc778b746d'
down_revision = '531997d75f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vendor_code', 'products', ['vendor_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vendor_code', 'products', type_='unique')
    # ### end Alembic commands ###
