"""Create a new field for documents in product model

Revision ID: 531997d75f68
Revises: 0172a3e2f2a0
Create Date: 2023-06-26 08:13:17.218787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531997d75f68'
down_revision = '0172a3e2f2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('document_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'document_url')
    # ### end Alembic commands ###
