"""Add deleting of products and subcategories when cateory is deleted

Revision ID: 5b768a87846f
Revises: 0f92971a1c3f
Create Date: 2023-06-15 08:13:20.312869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b768a87846f'
down_revision = '0f92971a1c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_parent_category_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_parent_category_id_fkey', 'categories', 'categories', ['parent_category_id'], ['id'])
    # ### end Alembic commands ###
