"""Add is_pickup for delivery_type model

Revision ID: 6bc08dd9566b
Revises: eee8ae7304f3
Create Date: 2023-03-27 07:50:06.834603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc08dd9566b'
down_revision = 'eee8ae7304f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service__delivery_types', sa.Column('is_pickup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service__delivery_types', 'is_pickup')
    # ### end Alembic commands ###
