"""Initiazlize models

Revision ID: 78927e043df4
Revises: 
Create Date: 2023-02-19 18:50:27.291868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78927e043df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_names',
    sa.Column('payload', sa.String(length=255), nullable=False),
    sa.Column('bookkeeping_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookkeeping_id')
    )
    op.create_index(op.f('ix_attribute_names_id'), 'attribute_names', ['id'], unique=False)
    op.create_table('attribute_values',
    sa.Column('payload', sa.String(length=255), nullable=False),
    sa.Column('bookkeeping_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookkeeping_id')
    )
    op.create_index(op.f('ix_attribute_values_id'), 'attribute_values', ['id'], unique=False)
    op.create_table('base_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('international_abbreviated', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_units_id'), 'base_units', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('quick_order', sa.Integer(), nullable=True),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('bookkeeping_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('discount < 100', name='check_discount_less_than_100'),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookkeeping_id'),
    sa.UniqueConstraint('order'),
    sa.UniqueConstraint('quick_order')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('manufacturers',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('bookkeeping_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookkeeping_id')
    )
    op.create_index(op.f('ix_manufacturers_id'), 'manufacturers', ['id'], unique=False)
    op.create_table('service__articles',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service__articles_id'), 'service__articles', ['id'], unique=False)
    op.create_table('service__delivery_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service__delivery_types_id'), 'service__delivery_types', ['id'], unique=False)
    op.create_table('service__partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service__partners_id'), 'service__partners', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('unp', sa.String(length=9), nullable=False),
    sa.Column('delivery_address', sa.String(length=128), nullable=True),
    sa.Column('legal_address', sa.String(length=128), nullable=True),
    sa.Column('IBAN', sa.String(length=34), nullable=True),
    sa.Column('BIC', sa.String(length=50), nullable=True),
    sa.Column('serving_bank', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value_id', sa.Integer(), nullable=True),
    sa.Column('name_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name_id'], ['attribute_names.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_id'], ['attribute_values.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributes_id'), 'attributes', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('status', postgresql.ENUM('P', 'S', 'c', 'C', name='order_status'), nullable=True),
    sa.Column('promo_code', sa.String(length=50), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=50), nullable=True),
    sa.Column('unp', sa.String(length=9), nullable=True),
    sa.Column('legal_address', sa.String(length=128), nullable=True),
    sa.Column('IBAN', sa.String(length=35), nullable=True),
    sa.Column('BIC', sa.String(length=50), nullable=True),
    sa.Column('serving_bank', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=128), nullable=True),
    sa.Column('house', sa.String(length=12), nullable=True),
    sa.Column('flat', sa.String(length=12), nullable=True),
    sa.Column('delivery_type_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['delivery_type_id'], ['service__delivery_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('products',
    sa.Column('status', postgresql.ENUM('A', 'W', 'O', name='product_status'), nullable=True),
    sa.Column('vendor_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('images', sa.String(), nullable=True),
    sa.Column('tax', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('count', sa.DECIMAL(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('price_with_discount', sa.DECIMAL(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('base_unit_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('bookkeeping_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('discount < 100', name='check_discount_lt_100'),
    sa.CheckConstraint('discount >= 0', name='check_discount_gte_0'),
    sa.ForeignKeyConstraint(['base_unit_id'], ['base_units.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookkeeping_id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('carts',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_count_should_be_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'user_id')
    )
    op.create_table('product_attribute',
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attribute_id', 'product_id')
    )
    op.create_table('product_order',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_count_should_be_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'order_id')
    )
    op.create_table('watch_lists',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_lists')
    op.drop_table('product_order')
    op.drop_table('product_attribute')
    op.drop_table('carts')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_attributes_id'), table_name='attributes')
    op.drop_table('attributes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service__partners_id'), table_name='service__partners')
    op.drop_table('service__partners')
    op.drop_index(op.f('ix_service__delivery_types_id'), table_name='service__delivery_types')
    op.drop_table('service__delivery_types')
    op.drop_index(op.f('ix_service__articles_id'), table_name='service__articles')
    op.drop_table('service__articles')
    op.drop_index(op.f('ix_manufacturers_id'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_base_units_id'), table_name='base_units')
    op.drop_table('base_units')
    op.drop_index(op.f('ix_attribute_values_id'), table_name='attribute_values')
    op.drop_table('attribute_values')
    op.drop_index(op.f('ix_attribute_names_id'), table_name='attribute_names')
    op.drop_table('attribute_names')
    # ### end Alembic commands ###
