"""Add is_new field for products

Revision ID: 8d74b94e8fdd
Revises: 96a59105e6ec
Create Date: 2023-05-22 09:49:00.077502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d74b94e8fdd'
down_revision = '96a59105e6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_new', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_new')
    # ### end Alembic commands ###
