"""Add new field price_on_request

Revision ID: 943806c24a1c
Revises: 531997d75f68
Create Date: 2023-07-16 07:12:05.314453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943806c24a1c'
down_revision = '531997d75f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_price_on_request', sa.Boolean(), nullable=True))
    op.alter_column('products', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('products', 'is_price_on_request')
    # ### end Alembic commands ###
