"""add banners

Revision ID: aaf9a39a0654
Revises: 24c9612c2434
Create Date: 2023-03-20 12:48:31.433422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf9a39a0654'
down_revision = '24c9612c2434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service__banners',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service__banners_id'), 'service__banners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service__banners_id'), table_name='service__banners')
    op.drop_table('service__banners')
    # ### end Alembic commands ###
