"""Add product_id in rquest call model

Revision ID: c335a69dcd44
Revises: 1e2c82f66fbe
Create Date: 2023-03-11 14:43:01.476486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c335a69dcd44'
down_revision = '1e2c82f66fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service__request_call', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key('service__request_call_product_id_fkey', 'service__request_call', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service__request_call_product_id_fkey', 'service__request_call', type_='foreignkey')
    op.drop_column('service__request_call', 'product_id')
    # ### end Alembic commands ###
