"""Add quck order attribute

Revision ID: c6557f83a714
Revises: bc8623dfdb6d
Create Date: 2023-02-19 17:15:07.376853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6557f83a714'
down_revision = 'bc8623dfdb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('quick_order', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'categories', ['quick_order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'quick_order')
    # ### end Alembic commands ###
