"""Add set_null for product_id in request calls

Revision ID: c83fc3649876
Revises: 5b768a87846f
Create Date: 2023-06-15 08:58:06.043803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83fc3649876'
down_revision = '5b768a87846f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service__request_call_product_id_fkey', 'service__request_call', type_='foreignkey')
    op.create_foreign_key(None, 'service__request_call', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service__request_call', type_='foreignkey')
    op.create_foreign_key('service__request_call_product_id_fkey', 'service__request_call', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
