"""add indexes

Revision ID: e1d6c81820ca
Revises: 00462ed12454
Create Date: 2025-03-06 12:51:51.739198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d6c81820ca'
down_revision = '00462ed12454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attributes_name_id'), 'attributes', ['name_id'], unique=False)
    op.create_index(op.f('ix_attributes_value_id'), 'attributes', ['value_id'], unique=False)
    op.drop_constraint('categories_quick_order_key', 'categories', type_='unique')
    op.create_index(op.f('ix_categories_quick_order'), 'categories', ['quick_order'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.drop_constraint('uq_vendor_code', 'products', type_='unique')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_is_new'), 'products', ['is_new'], unique=False)
    op.create_index(op.f('ix_products_vendor_code'), 'products', ['vendor_code'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_products_vendor_code'), table_name='products')
    op.drop_index(op.f('ix_products_is_new'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.create_unique_constraint('uq_vendor_code', 'products', ['vendor_code'])
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_categories_quick_order'), table_name='categories')
    op.create_unique_constraint('categories_quick_order_key', 'categories', ['quick_order'])
    op.drop_index(op.f('ix_attributes_value_id'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_name_id'), table_name='attributes')
    # ### end Alembic commands ###
