name: CD

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create an env file'
        run: echo '${{ secrets.CABEL_TORG_ENV_DEV }}' > backend/.env.dev

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rebuild conainers
        run: docker-compose -f docker-compose.dev.yaml up --build -d
