name: Deploy with Docker Compose

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Going to root dir of project.
        run: cd /root/cabel_torg/

      - name: Getting actual version of master branch.
        run: git pull

      - name: Waiting until git pull command is finished ...
        run: sleep 5s
        shell: bash

      - name: Rebuilding and restarting containers.
        run: docker-compose up --build -d

      - name: Waiting until docker-compose up if finished ...
        run: sleep 100s
        shell: bash

      - name: Clean unsed data.
        run: docker system prune -f

  rebuild-without-cache:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Going to root dir of project.
        run: cd /root/cabel_torg/

      - name: Getting actual version of master branch.
        run: git pull

      - name: Waiting until git pull command is finished ...
        run: sleep 5s
        shell: bash

      - name: Rebuilding containers without cache.
        run: docker-compose build --no-cache

      - name: Restarting containers.
        run: docker-compose up -d

      - name: Waiting until docker-compose up if finished ...
        run: sleep 100s
        shell: bash

      - name: Clean unsed data.
        run: docker system prune -f