name: Deploy with Docker Compose

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Go to root dir of project.
        run: cd /root/cabel_torg/

      - name: Get actual version of master branch.
        run: git pull

      - name: Waiting until git pull command is finished ...
        run: sleep 5s
        shell: bash

      - name: Rebuild and restart containers.
        run: docker-compose up --build -d
